
version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    deploy:
      replicas: 1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka-net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    deploy:
      replicas: 1
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka-net

  preprocessor:
    image: fem_preprocessor
    deploy:
      replicas: 1
      restart_policy:
        condition: none 
    networks:
      - kafka-net

  solver:
    image: fem_solver
    deploy:
      replicas: 1
    networks:
      - kafka-net

  postprocessor:
    image: fem_postprocessor
    deploy:
      replicas: 1
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: overlay
